### ISSUE TITLE
[Log] Reference map 'hauntedharvest-forge-refmap.json' for hauntedharvest.mixins.json could not be read.

### ISSUE THREAD

**Issue by Lucky-56** [MehVahdJukaar/TrickOrTreatMod#10]
While starting the game log says `Reference map 'hauntedharvest-forge-refmap.json' for hauntedharvest.mixins.json could not be read. If this is a development environment you can ignore this message`

at startup, assuming I'm not in a 'dev environment' this shouldn't happen

**Comment by MehVahdJukaar** [comment]
this should be fixed
