### ISSUE TITLE
Cant de-face pumpkin when used with Apotheosis

### ISSUE THREAD

**Issue by transbiod** [MehVahdJukaar/TrickOrTreatMod#21]
Hi, Aphotheosis adds shears that replace vannilla ones, so it just makes vanilla carved pumkin. Am i doing something wrong or is there no integration with modded shears?

**Comment by MehVahdJukaar** [comment]
sounds like an issue on their side. On forge to see if something is a shear i just use Forge API to check that using if they can perform a forge shear action with stack.canPerformAction(ToolActions.SHEARS_CARVE);

**Comment by transbiod** [comment]
Ok, i will test with shears from other mods. It's first time that i'm using this mod. so can you please help with the steps to make custom carved pumpkin? I place vanilla pumpkin, then use shears on it and interact with either sword or knife. Is this right?

**Comment by MehVahdJukaar** [comment]
Yes that's right

**Comment by MehVahdJukaar** [comment]
You can use your had too to open gui

**Comment by transbiod** [comment]
Ok, thanks! I will post my results after aditional testing

**Comment by transbiod** [comment]
Yeah, seems that one of my mods is messing with this feature, because all of the shears make vanilla carved pumpkin when used

**Comment by MehVahdJukaar** [comment]
By clicking their top,?

**Comment by transbiod** [comment]
O my god... I feel so stupid right now :D, but yes clicking on top of the pumpkin works! THANK YOU!!!
