### ISSUE TITLE
Config Option to Change Structure Frequency

### ISSUE THREAD

**Issue by Blunder-G** [MehVahdJukaar/TrickOrTreatMod#28]
I've seen so much Haunted Cabin/Barn in my world and it's really annoying. I couldn't see a config option to change rarity so it would be nice if us can determine it's frequency

**Comment by MehVahdJukaar** [comment]
what version are you using? the one with corn? if so i did increase its rarity quite a bit. Anyways structures are data driven and can only be changed with datapacks

**Comment by Blunder-G** [comment]
How can i lower structure spawn? Should i decrease spacing and seperation?

**Comment by MehVahdJukaar** [comment]
Increase
