### ISSUE TITLE
"The game crashed whilst rendering overlay"

### ISSUE THREAD

**Issue by stray-sparks** [MehVahdJukaar/TrickOrTreatMod#29]
This is on a custom modpack. It was working before updating these mods:
supplementaries
horse colors
quark
terrablender
create goggles
harvest with ease
sophisticatedcore
voicechat forge
create steam and rails
create misc and things
effortless building
no hostiles around campfire
redstone pen
spice of life sweet potato 

This is the error the launcher gives me:

```
The game crashed whilst rendering overlay
Error: java.lang.NoClassDefFoundError: Could not initialize class net.mehvahdjukaar.hauntedharvest.configs.CommonConfigs
```

Full error report is attached:
[crash-2023-04-02_16.56.50-client.txt](https://github.com/MehVahdJukaar/TrickOrTreatMod/files/11133784/crash-2023-04-02_16.56.50-client.txt)

**Comment by MehVahdJukaar** [comment]
I need the latest.log.
Be sure you have all your mods up to date not just some. This happens when you have some outdated dependencies
