### ISSUE TITLE
Placing a Carved Pumpkin causes a freeze, possibly related to a memory problem

### ISSUE THREAD

**Issue by mosharky** [MehVahdJukaar/TrickOrTreatMod#33]
An already placed Carved Pumpkin prevents the chunk from rendering at all. Placing one causes the game to freeze until you close it. There was no error in the log and no crash report.

MC: 1.20.1
Forge: 47.1.0
Haunted Harvest 3.1.9

![image](https://github.com/MehVahdJukaar/TrickOrTreatMod/assets/32606683/534c5e2d-7fe5-4342-873a-916ea1582b73)

**Comment by 0Navis0** [comment]
I get the same issue, here is the crash report.
https://pastebin.com/smtbczrU

**Comment by Kelpiesaurus** [comment]
I also got exit code: -805306369 and the invisible chunk after I used shears on the top of a pumpkin. When I destroyed the carved pumpkin and exited, then reopened the world, the chunk was visible again.

Almost forgot, here's my latest log right after shearing the pumpkin: https://pastebin.com/7Za7yvah

**Comment by MehVahdJukaar** [comment]
fixed
