### ISSUE TITLE
hauntedharvest-1.20-3.1.9-fabric.jar: Barns are broken

### ISSUE THREAD

**Issue by NoobiusMcGuffin** [MehVahdJukaar/TrickOrTreatMod#34]
The chest in the barn have no items in them and there seems to be an issue of a broken chunk that can spawn near the barn that causes blocks to be completely invisible above a certain Y level

**Comment by MehVahdJukaar** [comment]
hm i tried replicating this but couldnt. tried locating barns or placing new ones

**Comment by TheMagicalSC** [comment]
I've had a similar issue in the Forge version. I think it's an issue with Rubidium and Sodium, cause The Aether had a similar issue before it was fixed.
![2023-12-19_01 15 56](https://github.com/MehVahdJukaar/TrickOrTreatMod/assets/88447072/23ad949c-b378-437d-920a-489f294158e6)
![2023-12-19_01 16 15](https://github.com/MehVahdJukaar/TrickOrTreatMod/assets/88447072/d53f69c8-81d6-467c-8d45-e1ba9642da9b)

**Comment by MehVahdJukaar** [comment]
You do not have indium

**Comment by MehVahdJukaar** [comment]
This is caused by sodium. Their fault their issue
