### ISSUE TITLE
[1.20.1 Fabric] Crash from Supplementaries Flax Compat

### ISSUE THREAD

**Issue by Trent2087** [MehVahdJukaar/TrickOrTreatMod#45]
Description: Exception ticking world
java.lang.NoSuchFieldError: AGE
	at net.mehvahdjukaar.hauntedharvest.integration.SuppCompat.placeFlax(SuppCompat.java:33)
	at net.mehvahdjukaar.hauntedharvest.worldgen.FarmFieldFeature.generate(FarmFieldFeature.java:61)
https://hastebin.com/share/jevipacalu.yaml

For now I just changed crop in the flax fields configured feature to corn until its fixed, as that let it continue working.

**Comment by WildFyr16** [comment]
Yep, the same I issue just had with the latest version of Supplementaries. Seems to work fine on version 1.20-2.6.19 instead of latest 1.20-2.6.19-

**Comment by MehVahdJukaar** [comment]
Try new version
