### ISSUE TITLE
(1.19.2) Haunted Harvest carved pumpkins cause crash

### ISSUE THREAD

**Issue by PleaseInsertCoin** [MehVahdJukaar/TrickOrTreatMod#46]
I have a modpack running on a server with Haunted Harvest. It ran completely fine before, but after updating to the latest versions of the mods, carved pumpkins, specifically the ones from Haunted Harvest, crash my game immediately when loading them in or placing them. Not sure if this is a compatibility issue or if it's an issue with the newest version of this mod.

[crash-2023-11-04_11.14.28-client.txt](https://github.com/MehVahdJukaar/TrickOrTreatMod/files/13257013/crash-2023-11-04_11.14.28-client.txt)

**Comment by warrentode** [comment]
I'm experiencing the same error.

https://gist.github.com/warrentode/bf707af26da921534546700912f8cef4

**Comment by MehVahdJukaar** [comment]
Are you using known problematic mods like optifine or sodium?

**Comment by PleaseInsertCoin** [comment]
No, I am not using Optifine or Sodium. As far as I am aware all the mods I am using are pretty secure.

**Comment by MehVahdJukaar** [comment]
Ok then double check moonlight is on latest version

**Comment by MehVahdJukaar** [comment]
Tho I might have indeed messed it up for HH due to recent backports

**Comment by PleaseInsertCoin** [comment]
Yup, I am using the latest version of Moonlight for 1.19.2, still crashes.

**Comment by warrentode** [comment]
I'm not using Optifine or Sodium either. I had to roll back to Moonlight Lib 2.2.46 and Supplementaries 2.23.3 to correct the problem.

**Comment by MehVahdJukaar** [comment]
does updating moonlight fixes this issue?

**Comment by PleaseInsertCoin** [comment]
I just updated moonlight to the latest version (2.3.5) and it still crashes.

**Comment by warrentode** [comment]
Unfortunately, I also continue to crash with Moonlight Lib 2.3.5 in my test map.

**Comment by warrentode** [comment]
Your most recent update of Haunted Harvest works for me. Thank you for such a quick response.
