### ISSUE TITLE
[1.20.1] Thrown Eggs Ticking Entity

### ISSUE THREAD

**Issue by AetheriMC** [MehVahdJukaar/TrickOrTreatMod#50]
Minecraft v1.20.1
Forge v47.2.4
Haunted Harvest v1.20-3.1.18

Thrown eggs are apparently creating ticking entities which are promptly removed by Neruina.

![2024-01-18_11 43 22](https://github.com/MehVahdJukaar/TrickOrTreatMod/assets/64112227/401c533c-91da-48e9-9d97-a39a1b8c4dd6)

**Comment by MehVahdJukaar** [comment]
I need latest.log

**Comment by AetheriMC** [comment]
[latest.log](https://github.com/MehVahdJukaar/TrickOrTreatMod/files/13980170/latest.log)

Line 3493
![image](https://github.com/MehVahdJukaar/TrickOrTreatMod/assets/64112227/7747b5b0-413b-4f93-9467-8b648feefac6)

**Comment by MehVahdJukaar** [comment]
Are you using latest moonlight version?

**Comment by AetheriMC** [comment]
Ah. It's always the simplest solution...

Updating the moonlight library mod fixed the ticking entity issue. Thank you for the prompt assistance.
