### ISSUE TITLE
Suggestion: Paper Bag Disguise

### ISSUE THREAD

**Issue by captainphineas** [MehVahdJukaar/TrickOrTreatMod#59]
Paper bags will
- Hide player gamertag
- Pacify angered neutral mobs
- prevent enderman aggression by staring

probably not but could be cool/interesting (maybe configurable options??)
- display gui similar to pumpkin head??
- turn hostile mobs neutral to wearer??

**Comment by MehVahdJukaar** [comment]
the neutral stuff is interesting but a bit weird since pumpkins dont do that. name tag could be an intresting unique feature. i made it conigurable. will be available soon
